version: 2.1
orbs:
  golang: heroku/golang@0.0.10

workflows:
  ci:
    jobs:
      - golang/golangci-lint:
          version: "v1.18.0"
      - golang/test:
          version: "1.13"
      - golang/cover:
          version: "1.13"
